### PR TITLE
Add `delta` and `delta_token` for a single drive root

### PR DESCRIPTION
**Pull request by smndtrl**
Hej, great work with the 1.0 update. We talked in #354 about delta tokens.

I found one oddity when trying to get the delta  of a drive. There is no `.delta()` in `DrivesIdApiClient` only in  `DrivesItemsPathIdApiClient` which in turn would end up looking like this. 

```
client
  .drive("b!1oEIas-b4U6W99kfSoeuCsWxaE3M8_1Ntd6j7imn15Stw2E6t7n6SYmXmE1-hC75")
  .item_by_path("")
  .get_drive_item_delta()
```

with this addition you can use

```
client
  .drive("id")
  .delta()
```

### CODE REVIEW

**Comment by sreeise** [comment]
Hey @smndtrl thanks for making the contribution. 

So the request.rs files in all of the api implementations is generated code. If we need to manually add a request because its missing we should use a file called `manual_request.rs` in the same directory. Drives already has this in its folder.  This is where those methods should be added. This will make it so that when regenerating the apis these manually added requests to not get overwritten and subsequently removed.

The `manual_request.rs` file extends the implementations for both `DrivesIdApiClient` and `DrivesItemsIdApiClient` currently so you should be good to just add those under the `DrivesIdApiClient` impl.

As for the two specific methods the reason that not all of the api implementations have a `deltaToken` request is because, 1. They are not included in the OpenApi specs from which these are generated, 2. Because of the first reason, we added a deltaToken query parameter that can be added for all requests whenever it is needed so there is not a need to generate these methods on every client that has a delta method.

for instance if you added the following to manual_request.rs:

```
   get!(
        doc: "Invoke function delta",
        name: delta,
        path: "/drives/{{RID}}/root/delta()"
    );
```

You can then call this method by itself or by adding a delta token like so:

```
    let response = client.drive("id")
        .delta()
        .delta_token("delta_token")
        .send()
        .await?;
```

This would be the same thing as having a delta_token method. Hopefully that helps clear up some of the confusion on why some apis have deltaToken requests and some don't. Its mainly either those that do have deltaToken requests are manually added or they just happened to be included in the OpenApi config. Generally though I havnt seen those methods that often in the OpenApi configs.

Feel free to add both of those methods to `drives/manual_request.rs` and I will approve it regardless of what I mentioned above. The users/me/sites/groups drive api also has a manually implemented `delta_token` request so it makes it more consistent. but I wanted to provide you with the information on the delta_token query parameter because that might come in handy in the future.

**Review by sreeise — CHANGES_REQUESTED** [review]
Lets move these to the same impl of `DrivesIdApiClient` in `drives/manual_request.rs`

**Comment by smndtrl** [comment]
Thanks for the detailed explanation!

**Comment by sreeise** [comment]
Thanks!

**Pull request merged**
