### PR TITLE
Add a request pipeline and configuration for retries

### LINKED ISSUE #421: Retry functionality
Implement retry functionality for the client to retry requests. Cases that this implementation should solve and objectives: 
- Client is throttled and needs to check retry header to see when retry is possible. Same as 429 rate limits.
- 500 error codes have different possibilties and the Microsoft Graph Api may have their own way of returning certain 500 error codes. Some 500 errors are used in concert with a Retry-After header so that should be looked at. The 500 Internal server error will depend on the situation and error occuring. 
- Whenever there is a retry after header then always use that to figure out when to retry. 

Functionality:

- Retry after throttle using header value of time to wait. If possible, this should just be a flip of the switch to turn on. Meaning no other inputs should be required to be given except that this should be enabled (such passing true or false for enabled). 
- Backoff or retry policy that provides 
   - min time to retry
   - max time to retry, 
   - max retries tried - we want to stop trying to send requests when we reach this
-  backoff strategy - exponential backoff, and the retry after throttle mentioned above (name to be decided by who works on this). These strategies use the above policy inputs (min time/max time, etc)

Any other important use cases and implementation notes? Feedback welcome.

**Update**:

Implementation should include the following 2 retry types at the minimum and more can be added or updated later on as well:

- **Throttle Retry**: Handle retrying for when Microsoft throttles requests and sends back the 429 http error code and Retry-After header. The impl should check if the http code is a 429 and if it is then get the seconds from the Retry-After header, and wait the amount of seconds provided in the Retry-After header before retrying the request again. See https://learn.microsoft.com/en-us/graph/throttling#best-practices-to-handle-throttling
- **Exponential backoff**: retries requests exponentially, increasing the waiting time between retries up to a maximum backoff time. Each retry will have a wait time of 2x the previous wait time. 

There may be cases where these conflict with each other and we will need to come up with a way to deal with this such as not using any other retry except the throttle retry when a 429 response code is returned.

### PR DESCRIPTION
**Pull request by DevLazio**
Closes #421

### CODE REVIEW

**Comment by sreeise** [comment]
Hey @DevLazio this looks great. I apologize for not getting back to this sooner. I have been busy as of late.

This is my fault for not saying anything sooner, but version 2.0.0 is being released and you will probably have to deal with merge conflicts when merging master. 

This is awesome though. I appreciate the hard work on this.

**Comment by sreeise** [comment]
@DevLazio Hopefully the merge conflicts are not too bad. Everything looks good and ready to merge once the conflicts have been resolved.

**Review by sreeise — DISMISSED** [review]

**Comment by sreeise** [comment]
Working on the merge conflicts while @DevLazio is away to help out and try to get this merged.

**Review by sreeise — APPROVED** [review]

**Comment by Jeadie** [comment]
This PR makes `GraphClient` no longer `sync`.

**Pull request merged**
