### PR TITLE
Enable `AuthorizationCodeCredential` for `PublicClientApplication`

### PR DESCRIPTION
**Pull request by Jeadie**
- When using `graph-rs-sdk` for authentication a `PublicClientApplication` with `AuthorizationCodeCredential`, I ran into several issues.
- Only functional change is in `impl TokenCredentialExecutor for AuthorizationCodeCredential`'s `fn form_urlencode`. We no longer check for a missing or empty `client_secret`, as per docs,`'required for confidential web apps... Don't use the application secret in a native app or single page app because a client_secret can't be reliably stored on devices or web pages.'` (see https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow#request-an-access-token-with-a-client_secret).

### CODE REVIEW

**Review by sreeise — COMMENTED** [review]
How are you expecting to use the `AuthorizationCodeCredential` in a spa application? You wouldn't make a normal post token request to get an access token. The access token would come on the redirect from login.

Are you saying this is an issue with refreshing tokens?

**Comment by sreeise** [comment]
@Jeadie I think I see what the issue is. You want to use a spa based public client via authorization code credential. Your access token and refresh token both come on the redirect. But your AuthorizationCodeCredential doesn't use a client secret in this type of flow.  Is this correct?

Heres my concern about your PR, however. Taking the AuthorizationCodeCredential and making the client secret optional removes an important verification for those apps that use a client secret. Specifically non-spa based. I don't think thats the best way to go about doing this. Second, the AuthorizationCodeCredential struct performs http requests to get token which you would not do for the initial access token in a spa based app. You would do so with a refresh token. The original access and refresh token your getting would come from the redirect uri or a post to an endpoint after login. And not from passing an authorization code which the AuthorizationCodeCredential is specifically meant for.

Instead, what is most likely needed here is a new url builder for the initial sign in and a new type of credential. Most likely something like SpaAuthorizationUrlParameters and SpaCredential. 

The url parameter builder would be similar to `AuthCodeAuthorizationUrlParameters` and the `SpaCredential` would be similar to `AuthorizationCodeCredential` in several ways. But there are differences that warrant different types. For one, they offer different parameters and the second issue being that the SpaCredential should be created based on a token coming from the redirect uri instead of being created by passing the auth code. 

So there is some extra work that would be required for this to make it work correctly.

**Comment by sreeise** [comment]
@Jeadie Take a look at https://github.com/sreeise/graph-rs-sdk/pull/495 

This adds a credential for Spa applications using a public client.

**Comment by Jeadie** [comment]
We're attempting to have users (running a tool locally), retrieve a `AuthorizationCodeCredential` via a redirect_url to a server running locally in the tool. Users cannot have access to a client_secret or equivalent.

**Comment by sreeise** [comment]
> We're attempting to have users (running a tool locally), retrieve a `AuthorizationCodeCredential` via a redirect_url to a server running locally in the tool. Users cannot have access to a client_secret or equivalent.

Gotcha. Thanks for the response. I beleive #495 should solve this issue still. In that PR I made the PKCE required because thats what the auth flow says is required. But if its allowing you to do so without it I can make it optional. Let me know.

**Comment by sreeise** [comment]
Closing this out as the other work I mentioned got merged and I havn't heard anything back here. Let me know if there is an issue going forward.

**Pull request closed without merging**
